/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Planilla;

import Contratacion.VentanaEvaluarAspirantes;
import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Edwin Chocoy
 */
public class Modulo_Planilla extends javax.swing.JFrame {

    /**
     * Creates new form Modulo_Planilla
     */
    public Modulo_Planilla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelOpciones = new javax.swing.JPanel();
        label_CrearPlanilla = new javax.swing.JLabel();
        label_VerPlanillas = new javax.swing.JLabel();
        Panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelOpciones.setBackground(new java.awt.Color(34, 41, 50));

        label_CrearPlanilla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_CrearPlanilla.setForeground(new java.awt.Color(166, 166, 166));
        label_CrearPlanilla.setText("Crear Planilla");
        label_CrearPlanilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_CrearPlanillaMousePressed(evt);
            }
        });

        label_VerPlanillas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_VerPlanillas.setForeground(new java.awt.Color(166, 166, 166));
        label_VerPlanillas.setText("Ver Planillas");
        label_VerPlanillas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_VerPlanillasMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOpcionesLayout = new javax.swing.GroupLayout(jPanelOpciones);
        jPanelOpciones.setLayout(jPanelOpcionesLayout);
        jPanelOpcionesLayout.setHorizontalGroup(
            jPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_CrearPlanilla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_VerPlanillas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelOpcionesLayout.setVerticalGroup(
            jPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(label_CrearPlanilla)
                .addGap(18, 18, 18)
                .addComponent(label_VerPlanillas)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_CrearPlanillaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_CrearPlanillaMousePressed
        // TODO add your handling code here:

        setLblColor(label_CrearPlanilla);
        
        VentanaCrearPlanilla v = new VentanaCrearPlanilla();
        v.setSize(Panel.getSize());
        v.setLocation(0, 0);
        Panel.removeAll();
        Panel.add(v);
        Panel.repaint();
        

        resetLblColor(label_VerPlanillas);
    }//GEN-LAST:event_label_CrearPlanillaMousePressed

    private void label_VerPlanillasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_VerPlanillasMousePressed
        // TODO add your handling code here:
        setLblColor(label_VerPlanillas);
        VentanaPlanillaGuardada v = new VentanaPlanillaGuardada();
        v.setSize(Panel.getSize());
        v.setLocation(0, 0);
        Panel.removeAll();
        Panel.add(v);
        Panel.repaint();
        
        resetLblColor(label_CrearPlanilla);


    }//GEN-LAST:event_label_VerPlanillasMousePressed
    
    public void setLblColor(JLabel lb){
        lb.setForeground(new Color(48,201,235));
    }
    
    public void resetLblColor(JLabel lb){
        lb.setForeground(new Color(166,166,166));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modulo_Planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modulo_Planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modulo_Planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modulo_Planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modulo_Planilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JLabel label_CrearPlanilla;
    private javax.swing.JLabel label_VerPlanillas;
    // End of variables declaration//GEN-END:variables
}
