/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import Contratacion.Modulo_Contratacion;
import Estructura.Modulo_Estructura;
import Planilla.Modulo_Planilla;
import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Edwin Chocoy
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCentral = new javax.swing.JPanel();
        jPanelTexto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelOpciones = new javax.swing.JPanel();
        jLabelEstructura = new javax.swing.JLabel();
        jLabelContratacion = new javax.swing.JLabel();
        jLabelPlanila = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCentral.setBackground(new java.awt.Color(48, 201, 235));

        jPanelTexto.setBackground(new java.awt.Color(48, 201, 235));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Recursos Humanos");

        javax.swing.GroupLayout jPanelTextoLayout = new javax.swing.GroupLayout(jPanelTexto);
        jPanelTexto.setLayout(jPanelTextoLayout);
        jPanelTextoLayout.setHorizontalGroup(
            jPanelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTextoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanelTextoLayout.setVerticalGroup(
            jPanelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTextoLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanelOpciones.setBackground(new java.awt.Color(255, 255, 255));

        jLabelEstructura.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelEstructura.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEstructura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_Department_18px.png"))); // NOI18N
        jLabelEstructura.setText("Estructura");
        jLabelEstructura.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelEstructura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelEstructuraMousePressed(evt);
            }
        });

        jLabelContratacion.setBackground(new java.awt.Color(48, 201, 235));
        jLabelContratacion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelContratacion.setForeground(new java.awt.Color(0, 0, 0));
        jLabelContratacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_Name_Tag_18px.png"))); // NOI18N
        jLabelContratacion.setText("Contratacion");
        jLabelContratacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelContratacionMousePressed(evt);
            }
        });

        jLabelPlanila.setBackground(new java.awt.Color(48, 201, 235));
        jLabelPlanila.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelPlanila.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPlanila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_People_18px.png"))); // NOI18N
        jLabelPlanila.setText("Planilla");
        jLabelPlanila.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelPlanilaMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Menu");

        javax.swing.GroupLayout jPanelOpcionesLayout = new javax.swing.GroupLayout(jPanelOpciones);
        jPanelOpciones.setLayout(jPanelOpcionesLayout);
        jPanelOpcionesLayout.setHorizontalGroup(
            jPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOpcionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelContratacion)
                    .addComponent(jLabelEstructura, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPlanila))
                .addGap(246, 246, 246))
            .addGroup(jPanelOpcionesLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOpcionesLayout.setVerticalGroup(
            jPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEstructura)
                .addGap(18, 18, 18)
                .addComponent(jLabelContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelPlanila)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelOpciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addComponent(jPanelTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelContratacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelContratacionMousePressed
        // TODO add your handling code here:
        setLblColor(jLabelContratacion);
        
        Modulo_Contratacion v = new Modulo_Contratacion();
        v.setVisible(true);
        
        resetLblColor(jLabelEstructura);
        resetLblColor(jLabelPlanila);
    }//GEN-LAST:event_jLabelContratacionMousePressed

    private void jLabelEstructuraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEstructuraMousePressed
        // TODO add your handling code here:
        setLblColor(jLabelEstructura);
        
        new Modulo_Estructura().setVisible(true);
        
        resetLblColor(jLabelContratacion);
        resetLblColor(jLabelPlanila);
    }//GEN-LAST:event_jLabelEstructuraMousePressed

    private void jLabelPlanilaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPlanilaMousePressed
        // TODO add your handling code here:
        setLblColor(jLabelPlanila);
        
        new Modulo_Planilla().setVisible(true);
        
        resetLblColor(jLabelContratacion);
        resetLblColor(jLabelEstructura);
    }//GEN-LAST:event_jLabelPlanilaMousePressed
    
    public void setLblColor(JLabel lb){
        lb.setForeground(new Color(0,51,153));

    }
    
    public void resetLblColor(JLabel lb){
        lb.setForeground(new Color(0,0,0));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelContratacion;
    private javax.swing.JLabel jLabelEstructura;
    private javax.swing.JLabel jLabelPlanila;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JPanel jPanelTexto;
    // End of variables declaration//GEN-END:variables
}
