/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Contratacion;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Hugo
 */
public class Modulo_Contratacion extends javax.swing.JFrame {

    /**
     * Creates new form Prueba
     */
    public Modulo_Contratacion() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        label_IngresarAspirante = new javax.swing.JLabel();
        label_CrearReclutamiento = new javax.swing.JLabel();
        label_CrearPropuesta = new javax.swing.JLabel();
        label_AsignarCalificaciones = new javax.swing.JLabel();
        label_Evaluar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setPreferredSize(new java.awt.Dimension(719, 0));

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(34, 41, 50));

        label_IngresarAspirante.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_IngresarAspirante.setForeground(new java.awt.Color(166, 166, 166));
        label_IngresarAspirante.setText("Ingresar Aspirante");
        label_IngresarAspirante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_IngresarAspiranteMousePressed(evt);
            }
        });

        label_CrearReclutamiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_CrearReclutamiento.setForeground(new java.awt.Color(166, 166, 166));
        label_CrearReclutamiento.setText("Crear Reclutamiento");
        label_CrearReclutamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_CrearReclutamientoMousePressed(evt);
            }
        });

        label_CrearPropuesta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_CrearPropuesta.setForeground(new java.awt.Color(166, 166, 166));
        label_CrearPropuesta.setText("Crear Propuesta");
        label_CrearPropuesta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_CrearPropuestaMousePressed(evt);
            }
        });

        label_AsignarCalificaciones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_AsignarCalificaciones.setForeground(new java.awt.Color(166, 166, 166));
        label_AsignarCalificaciones.setText("Asignar Calificaciones");
        label_AsignarCalificaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_AsignarCalificacionesMousePressed(evt);
            }
        });

        label_Evaluar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_Evaluar.setForeground(new java.awt.Color(166, 166, 166));
        label_Evaluar.setText("Evaluar");
        label_Evaluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_EvaluarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_CrearPropuesta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_CrearReclutamiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_IngresarAspirante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_AsignarCalificaciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Evaluar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(label_CrearPropuesta)
                .addGap(18, 18, 18)
                .addComponent(label_CrearReclutamiento)
                .addGap(18, 18, 18)
                .addComponent(label_IngresarAspirante)
                .addGap(18, 18, 18)
                .addComponent(label_AsignarCalificaciones)
                .addGap(18, 18, 18)
                .addComponent(label_Evaluar)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_IngresarAspiranteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_IngresarAspiranteMousePressed
        // TODO add your handling code here:
        setLblColor(label_IngresarAspirante);
        
        VentanaAsignacionAspirante v = new VentanaAsignacionAspirante();
        v.setSize(Panel.getSize());
        v.setLocation(0, 0);
        Panel.removeAll();
        Panel.add(v);
        Panel.repaint();
        
        resetLblColor(label_CrearReclutamiento);
        resetLblColor(label_CrearPropuesta);
        resetLblColor(label_Evaluar);
        resetLblColor(label_AsignarCalificaciones);
    }//GEN-LAST:event_label_IngresarAspiranteMousePressed

    private void label_CrearReclutamientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_CrearReclutamientoMousePressed
        // TODO add your handling code here:
        setLblColor(label_CrearReclutamiento);
        
        VentanaCrearReclutamiento v = new VentanaCrearReclutamiento();
        v.setSize(Panel.getSize());
        v.setLocation(0, 0);
        Panel.removeAll();
        Panel.add(v);
        Panel.repaint();
        
        resetLblColor(label_IngresarAspirante);
        resetLblColor(label_CrearPropuesta);
        resetLblColor(label_Evaluar);
        resetLblColor(label_AsignarCalificaciones);

    }//GEN-LAST:event_label_CrearReclutamientoMousePressed

    private void label_CrearPropuestaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_CrearPropuestaMousePressed
        // TODO add your handling code here:

        setLblColor(label_CrearPropuesta);
        
        VentanaCrearPropuesta v = new VentanaCrearPropuesta();
        v.setSize(Panel.getSize());
        v.setLocation(0, 0);
        Panel.removeAll();
        Panel.add(v);
        Panel.repaint();
        
        resetLblColor(label_IngresarAspirante);
        resetLblColor(label_CrearReclutamiento);
        resetLblColor(label_Evaluar);
        resetLblColor(label_AsignarCalificaciones);
    }//GEN-LAST:event_label_CrearPropuestaMousePressed

    private void label_AsignarCalificacionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_AsignarCalificacionesMousePressed
        // TODO add your handling code here:
        setLblColor(label_AsignarCalificaciones);
        
        VentanaAsignarCalificaciones v = new VentanaAsignarCalificaciones();
        v.setSize(Panel.getSize());
        v.setLocation(0, 0);
        Panel.removeAll();
        Panel.add(v);
        Panel.repaint();
        
        resetLblColor(label_IngresarAspirante);
        resetLblColor(label_CrearReclutamiento);
        resetLblColor(label_Evaluar);
        resetLblColor(label_CrearPropuesta);
    }//GEN-LAST:event_label_AsignarCalificacionesMousePressed

    private void label_EvaluarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_EvaluarMousePressed
        // TODO add your handling code here:
        setLblColor(label_Evaluar);
        
        VentanaEvaluarAspirantes v = new VentanaEvaluarAspirantes();
        v.setSize(Panel.getSize());
        v.setLocation(0, 0);
        Panel.removeAll();
        Panel.add(v);
        Panel.repaint();
        
        resetLblColor(label_IngresarAspirante);
        resetLblColor(label_CrearReclutamiento);
        resetLblColor(label_AsignarCalificaciones);
        resetLblColor(label_CrearPropuesta);
    }//GEN-LAST:event_label_EvaluarMousePressed
    
    public void setLblColor(JLabel lb){
        lb.setForeground(new Color(48,201,235));
    }
    
    public void resetLblColor(JLabel lb){
        lb.setForeground(new Color(166,166,166));
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modulo_Contratacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modulo_Contratacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modulo_Contratacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modulo_Contratacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modulo_Contratacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_AsignarCalificaciones;
    private javax.swing.JLabel label_CrearPropuesta;
    private javax.swing.JLabel label_CrearReclutamiento;
    private javax.swing.JLabel label_Evaluar;
    private javax.swing.JLabel label_IngresarAspirante;
    // End of variables declaration//GEN-END:variables
}
